name: Check code style for plugin

on: [push, pull_request]

jobs:

  Check-Code-Style-for-Plugin-Processing-R:

    runs-on: ubuntu-latest

    steps:

        - name: Checkout
          uses: actions/checkout@v4

        - uses: psf/black@stable
          with:
            options: "--check --verbose"
