name: Check code style for plugin

on: [push, pull_request]

jobs:

  Check-Code-Style-for-Plugin-Processing-R:

    runs-on: ubuntu-latest

    steps:

        - name: Checkout
          uses: actions/checkout@v4

        - uses: psf/black@stable
          with:
            options: "--check --verbose --line-length 120"
            src: "./processing_r"
        
        - uses: isort/isort-action@v1
          with:
            configuration: "--check-only --diff --profile black --line-width 120" 
            sort-paths: "./processing_r"
   